"""baseline: create all tables

Revision ID: 1b02d74254e5
Revises: 
Create Date: 2026-04-17 16:52:46.889964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b02d74254e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    # If the 'users' table already exists the DB was bootstrapped by init_db.py
    # (or a previous deployment).  Skip all CREATE TABLE statements — the
    # catch-up migration e3a1f9b2c8d4 handles any missing columns on those DBs.
    if sa.inspect(bind).has_table('users'):
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_styles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('best_for', sa.JSON(), nullable=True),
    sa.Column('visual_layout', sa.String(), nullable=True),
    sa.Column('psychology', sa.Text(), nullable=True),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('lighting', sa.String(), nullable=True),
    sa.Column('composition', sa.String(), nullable=True),
    sa.Column('design_style', sa.String(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_usage_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('api_calls', sa.Integer(), nullable=False),
    sa.Column('ads_returned', sa.Integer(), nullable=False),
    sa.Column('ads_saved', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_logs_date'), 'api_usage_logs', ['date'], unique=False)
    op.create_table('brand_scrapes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=False),
    sa.Column('page_id', sa.String(), nullable=False),
    sa.Column('page_name', sa.String(), nullable=True),
    sa.Column('page_url', sa.String(), nullable=False),
    sa.Column('total_ads', sa.Integer(), nullable=True),
    sa.Column('media_downloaded', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_scrapes_brand_name'), 'brand_scrapes', ['brand_name'], unique=False)
    op.create_table('brands',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('secondary_color', sa.String(), nullable=True),
    sa.Column('highlight_color', sa.String(), nullable=True),
    sa.Column('voice', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('demographics', sa.Text(), nullable=True),
    sa.Column('pain_points', sa.Text(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facebook_campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('objective', sa.String(), nullable=False),
    sa.Column('budget_type', sa.String(), nullable=False),
    sa.Column('budget_schedule_type', sa.String(), nullable=True),
    sa.Column('daily_budget', sa.Integer(), nullable=True),
    sa.Column('lifetime_budget', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bid_strategy', sa.String(), nullable=True),
    sa.Column('special_ad_categories', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('fb_campaign_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_blacklist',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_blacklist_keyword'), 'keyword_blacklist', ['keyword'], unique=True)
    op.create_table('page_blacklist',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('page_name', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_blacklist_page_name'), 'page_blacklist', ['page_name'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('prompts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('verticals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verticals_name'), 'verticals', ['name'], unique=True)
    op.create_table('winning_ads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('recreation_prompt', sa.Text(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('subject_matter', sa.String(), nullable=True),
    sa.Column('copy_analysis', sa.Text(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('design_style', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('structural_analysis', sa.Text(), nullable=True),
    sa.Column('layering', sa.Text(), nullable=True),
    sa.Column('template_structure', sa.JSON(), nullable=True),
    sa.Column('color_palette', sa.JSON(), nullable=True),
    sa.Column('typography_system', sa.JSON(), nullable=True),
    sa.Column('copy_patterns', sa.JSON(), nullable=True),
    sa.Column('visual_elements', sa.JSON(), nullable=True),
    sa.Column('template_category', sa.String(), nullable=True),
    sa.Column('blueprint_json', sa.JSON(), nullable=True),
    sa.Column('blueprint_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand_profiles',
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['customer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('brand_id', 'profile_id')
    )
    op.create_table('brand_scraped_ads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('brand_scrape_id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('page_name', sa.String(), nullable=True),
    sa.Column('page_link', sa.String(), nullable=True),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('ad_copy', sa.Text(), nullable=True),
    sa.Column('cta_text', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('media_urls', sa.JSON(), nullable=True),
    sa.Column('original_media_urls', sa.JSON(), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('ad_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['brand_scrape_id'], ['brand_scrapes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_scraped_ads_external_id'), 'brand_scraped_ads', ['external_id'], unique=False)
    op.create_table('facebook_adsets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('optimization_goal', sa.String(), nullable=False),
    sa.Column('budget_schedule_type', sa.String(), nullable=True),
    sa.Column('daily_budget', sa.Integer(), nullable=True),
    sa.Column('lifetime_budget', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bid_strategy', sa.String(), nullable=True),
    sa.Column('bid_amount', sa.Integer(), nullable=True),
    sa.Column('targeting', sa.JSON(), nullable=True),
    sa.Column('pixel_id', sa.String(), nullable=True),
    sa.Column('conversion_event', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('fb_adset_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['facebook_campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facebook_pages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('page_name', sa.String(), nullable=False),
    sa.Column('page_url', sa.String(), nullable=True),
    sa.Column('vertical_id', sa.String(), nullable=True),
    sa.Column('total_ads', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facebook_pages_page_name'), 'facebook_pages', ['page_name'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_shots', sa.JSON(), nullable=True),
    sa.Column('default_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('permission_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('saved_searches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('negative_keywords', sa.JSON(), nullable=True),
    sa.Column('vertical_id', sa.String(), nullable=True),
    sa.Column('search_type', sa.String(), nullable=True),
    sa.Column('schedule_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ads_requested', sa.Integer(), nullable=True),
    sa.Column('ads_returned', sa.Integer(), nullable=True),
    sa.Column('ads_new', sa.Integer(), nullable=True),
    sa.Column('ads_duplicate', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('search_query', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('negative_keywords', sa.JSON(), nullable=True),
    sa.Column('vertical_id', sa.String(), nullable=True),
    sa.Column('total_ads_found', sa.Integer(), nullable=True),
    sa.Column('filtered_by_page_blacklist', sa.Integer(), nullable=True),
    sa.Column('filtered_by_keyword_blacklist', sa.Integer(), nullable=True),
    sa.Column('final_ads_saved', sa.Integer(), nullable=True),
    sa.Column('new_pages_blacklisted', sa.JSON(), nullable=True),
    sa.Column('api_calls_made', sa.Integer(), nullable=True),
    sa.Column('search_type', sa.String(), nullable=True),
    sa.Column('execution_time_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_logs_date'), 'search_logs', ['date'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('facebook_ads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('adset_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('creative_name', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('video_id', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('bodies', sa.JSON(), nullable=True),
    sa.Column('headlines', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cta', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('fb_ad_id', sa.String(), nullable=True),
    sa.Column('fb_creative_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['adset_id'], ['facebook_adsets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_ads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('cta', sa.String(), nullable=True),
    sa.Column('size_name', sa.String(), nullable=True),
    sa.Column('dimensions', sa.String(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('ad_bundle_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('video_id', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['winning_ads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraped_ads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=True),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('ad_copy', sa.Text(), nullable=True),
    sa.Column('cta_text', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('ad_link', sa.String(), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('seen_count', sa.Integer(), nullable=True),
    sa.Column('search_id', sa.String(), nullable=True),
    sa.Column('facebook_page_id', sa.String(), nullable=True),
    sa.Column('is_saved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['facebook_page_id'], ['facebook_pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['search_id'], ['saved_searches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_ads_content_hash'), 'scraped_ads', ['content_hash'], unique=True)
    op.create_index(op.f('ix_scraped_ads_external_id'), 'scraped_ads', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraped_ads_external_id'), table_name='scraped_ads')
    op.drop_index(op.f('ix_scraped_ads_content_hash'), table_name='scraped_ads')
    op.drop_table('scraped_ads')
    op.drop_table('generated_ads')
    op.drop_table('facebook_ads')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_search_logs_date'), table_name='search_logs')
    op.drop_table('search_logs')
    op.drop_table('saved_searches')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('products')
    op.drop_index(op.f('ix_facebook_pages_page_name'), table_name='facebook_pages')
    op.drop_table('facebook_pages')
    op.drop_table('facebook_adsets')
    op.drop_index(op.f('ix_brand_scraped_ads_external_id'), table_name='brand_scraped_ads')
    op.drop_table('brand_scraped_ads')
    op.drop_table('brand_profiles')
    op.drop_table('winning_ads')
    op.drop_index(op.f('ix_verticals_name'), table_name='verticals')
    op.drop_table('verticals')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('prompts')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_page_blacklist_page_name'), table_name='page_blacklist')
    op.drop_table('page_blacklist')
    op.drop_index(op.f('ix_keyword_blacklist_keyword'), table_name='keyword_blacklist')
    op.drop_table('keyword_blacklist')
    op.drop_table('facebook_campaigns')
    op.drop_table('customer_profiles')
    op.drop_table('brands')
    op.drop_index(op.f('ix_brand_scrapes_brand_name'), table_name='brand_scrapes')
    op.drop_table('brand_scrapes')
    op.drop_index(op.f('ix_api_usage_logs_date'), table_name='api_usage_logs')
    op.drop_table('api_usage_logs')
    op.drop_table('ad_styles')
    # ### end Alembic commands ###
